# .github/workflows/release.yml
name: Release Build

on:
  push:
    tags:
      - 'v*'  # Только для тэгов вида v1.0, v0.1.3 и т.п.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install rpm tools
      run: sudo apt-get update && sudo apt-get install -y rpm

    - name: Configure project
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --target all

    - name: Package DEB and RPM
      run: |
        cd build
        cpack -G DEB
        cpack -G RPM

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.deb
          build/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
