name: Release solver

on:
  push:
    tags:
      - "*" 

permissions:
  contents: write  

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake rpm dpkg-dev

      - name: Configure build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build solver
        run: cmake --build build --target solver

      - name: Package with CPack
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM
          cpack -G ZIP

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

